version: "3.7"

services:
  pg-db:
    image: postgres:17
    container_name: pg-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: uniform
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart:
        unless-stopped
    networks:
      uniform-network:
volumes:
  pg-data:
networks:
  uniform-network:
    driver: bridge